### ISSUE TITLE
Constants for ColorMode? 

### ISSUE THREAD

**Issue by jochenkirstaetter** [RickStrahl/WestWind.WebView.HtmlToPdf#2]
Just thinking whether in might be more intuitive and safer to provide constants for ColorMode instead of free ranging string values?

**Comment by RickStrahl** [comment]
Yeah all of the properties should be constants, but was lazy because I was playing with a bunch of different backends. Will eventually do that.

**Comment by RickStrahl** [comment]
Fixed. 

Updated all multi-set PrintSettings values with enums.
