### ISSUE TITLE
Invalid window handle. (Exception from HRESULT: 0x80070578)

### ISSUE THREAD

**Issue by lucaswhob** [RickStrahl/WestWind.WebView.HtmlToPdf#3]
Hello My Friend I Use Your Guide To Use Headless WebView2 
I Use This Code :
` private IntPtr HWND_MESSAGE = new IntPtr(-3); CoreWebView2Environment webView2Environment = CoreWebView2Environment.CreateAsync(null, AppContext.BaseDirectory + "\\whatsappdata\\" + workingdirectory).GetAwaiter().GetResult(); maincontroller =  await webView2Environment.CreateCoreWebView2ControllerAsync(HWND_MESSAGE);` 
But Error Run WebView2 From IIs 
This Simple WinForm Application 
Locally Run Good But Run From IIs Exception Throw

**Comment by RickStrahl** [comment]
You need to make sure you use a Windows account. I believe it won't work with IIS_APPLICATIONPOOLIDENTITY as there are permissions issues. It works for me with NETWORK SERVICE/SYSTEM or actual user account assuming you have permissions to write out the environment folder (you can specify a location).
