### ISSUE TITLE
Do all images need to be base64 embedded?

### ISSUE THREAD

**Issue by fabioparra** [RickStrahl/WestWind.WebView.HtmlToPdf#5]
Hi @RickStrahl, I tested your examples with loading an image from an https URL, but the image did not load. Do you have any idea why? It seems that images are only loaded with src="data:image/png;base64,...

**Comment by RickStrahl** [comment]
How big is your embedded data? There's a bug in the WebView control that if the embedded data is larger than 2mb it won't render.

https://github.com/MicrosoftEdge/WebView2Feedback/issues/4251   (related)

This limit applies for a number of things not just image embedding but also for string navigation and POST buffer capture.

**Comment by RickStrahl** [comment]
Closing since no response.
